"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { incidents } from "../management-data";
import { monitoringWorkers } from "../monitoring-data";
import { getSensorStatuses, initialTelemetry } from "../telemetry-data";
import "../dashboard.css";

const nav = [["Overview", "/dashboard", "▦"], ["Live Monitoring", "/dashboard/monitoring", "◉"], ["Vehicles", "/dashboard/vehicles", "▱"], ["Workers", "/dashboard/workers", "♙"], ["Safety Alerts", "/dashboard/alerts", "△"], ["Analytics", "/dashboard/analytics", "⌁"], ["Reports", "/dashboard/reports", "▤"], ["Settings", "/dashboard/settings", "⚙"]];

function Brand() { return <Link className="dashboard-brand" href="/"><span className="dashboard-logo" aria-hidden="true"><i /><i /><i /></span><span>Mine<span>Safe</span></span></Link>; }

function Shell({ children }: { children: React.ReactNode }) { return <div className="dashboard-shell analytics-page"><aside className="dashboard-sidebar"><Brand /><div className="sidebar-label">Workspace</div><nav>{nav.map(([label, href, icon]) => <Link className={label === "Analytics" ? "active" : ""} href={href} key={label}><span className="sidebar-text-icon">{icon}</span>{label}{label === "Safety Alerts" && <b className="nav-count">4</b>}</Link>)}</nav><div className="sidebar-bottom"><div className="shift-card"><span className="shift-pulse" /><div><strong>Day shift active</strong><small>07:00 — 19:00 IST</small></div></div><a className="sidebar-help" href="mailto:safety-ops@minesafe.example">Need help? <span>Contact safety ops ↗</span></a></div></aside><div className="dashboard-main"><header className="dashboard-header"><div className="mobile-brand"><Brand /></div><div className="header-title"><p>MineSafe / Safety intelligence</p><h1>Safety Analytics</h1></div><div className="header-actions"><div className="site-selector"><span className="site-pin">+</span><span><small>Current site</small>Singareni Mine — Site 04</span></div><span className="header-divider" /><span className="avatar">RK</span></div></header><main className="dashboard-content">{children}</main><footer className="dashboard-footer"><span>MineSafe Operations Console v1.0</span><span>Demo analytics · Simulated sensor data <i /></span></footer></div></div>; }

export default function AnalyticsPage() {
  const [sampleTick, setSampleTick] = useState(0);
  useEffect(() => { const interval = window.setInterval(() => setSampleTick((current) => current + 1), 4000); return () => window.clearInterval(interval); }, []);
  const safeWorkers = monitoringWorkers.filter((worker) => worker.safety === "Clear").length;
  const workersAtRisk = monitoringWorkers.filter((worker) => worker.safety !== "Clear").length;
  const sensorHealth = initialTelemetry.flatMap((truck) => Object.values(getSensorStatuses(truck.sensor))).filter((status) => status === "NORMAL").length;
  const sensorTotal = initialTelemetry.length * 3;
  const eventBars = [42, 58, 46, 74, 61, 88, 68].map((value, index) => Math.min(100, value + (sampleTick % 3) * (index % 2 === 0 ? 2 : -1)));
  return <Shell><section className="management-intro"><div><p className="dashboard-eyebrow"><span /> Safety intelligence · DEMO MODE</p><h2>Operational analytics</h2><p>Translate live worker, vehicle, and sensor signals into a clear safety picture for the shift.</p></div><span className="monitoring-system"><i /> DATA STREAM HEALTHY</span></section><section className="analytics-metrics"><div><strong>{monitoringWorkers.length}</strong><span>Tracked workers</span><small>Across active zones</small></div><div><strong>{safeWorkers}</strong><span>Safety clear</span><small>{Math.round((safeWorkers / monitoringWorkers.length) * 100)}% of roster</small></div><div className="analytics-warning"><strong>{workersAtRisk}</strong><span>Need attention</span><small>Supervisor review</small></div><div><strong>{Math.round((sensorHealth / sensorTotal) * 100)}%</strong><span>Sensor health</span><small>HC-SR04 · MPU6050 · GPS</small></div></section><div className="analytics-grid"><section className="panel analytics-chart-panel"><div className="panel-header"><div><p className="panel-kicker">Safety events</p><h2>Shift activity trend</h2></div><span className="trend-change">Last 7 readings</span></div><div className="analytics-chart"><div className="analytics-y-axis"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div><div className="analytics-bars">{eventBars.map((height, index) => <div className="analytics-bar-column" key={index}><i style={{ height: `${height}%` }} /><small>{["06", "08", "10", "12", "14", "16", "18"][index]}:00</small></div>)}</div></div></section><section className="panel analytics-status-panel"><div className="panel-header"><div><p className="panel-kicker">Current risk posture</p><h2>Safety overview</h2></div><span className="status-chip status-chip-normal"><i /> LOW RISK</span></div><div className="analytics-score"><strong>82</strong><span>/ 100 safety score</span></div><div className="analytics-progress"><span style={{ width: "82%" }} /></div><p>Core telemetry is reporting normally. One worker requires a safety check and existing alerts remain under review.</p><Link className="panel-link" href="/dashboard/alerts">Review active alerts ↗</Link></section></div><section className="panel analytics-events"><div className="panel-header"><div><p className="panel-kicker">Recent safety signals</p><h2>Events requiring context</h2></div><Link className="panel-link" href="/dashboard/monitoring">Open monitoring ↗</Link></div><div className="analytics-event-list">{incidents.slice(0, 3).map((incident) => <div key={incident.id}><span className={`severity severity-${incident.severity.toLowerCase()}`} /><div><strong>{incident.type}</strong><small>{incident.location} · {incident.dateTime}</small></div><span className={`risk risk-${incident.severity.toLowerCase()}`}>{incident.severity}</span></div>)}</div></section></Shell>;
}
