"use client";

import { startTransition, useEffect, useState } from "react";
import Link from "next/link";
import { incidents, type IncidentStatus, type Severity } from "../management-data";
import "../dashboard.css";

const nav = [["Overview", "/dashboard", "▦"], ["Live Monitoring", "/dashboard/monitoring", "◉"], ["Vehicles", "/dashboard/vehicles", "▱"], ["Workers", "/dashboard/workers", "♙"], ["Safety Alerts", "/dashboard/alerts", "△"], ["Analytics", "/dashboard/analytics", "⌁"], ["Reports", "/dashboard/reports", "▤"], ["Settings", "/dashboard/settings", "⚙"]];
const statuses: (IncidentStatus | "All")[] = ["All", "Open", "Under investigation", "Resolved", "Closed"];
const severities: (Severity | "All")[] = ["All", "Critical", "High", "Medium", "Low"];
function Brand() { return <Link className="dashboard-brand" href="/"><span className="dashboard-logo" aria-hidden="true"><i /><i /><i /></span><span>Mine<span>Safe</span></span></Link>; }
function Shell({ children }: { children: React.ReactNode }) { return <div className="dashboard-shell management-page"><aside className="dashboard-sidebar"><Brand /><div className="sidebar-label">Workspace</div><nav>{nav.map(([label, href, icon]) => <Link className={label === "Reports" ? "active" : ""} href={href} key={label}><span className="sidebar-text-icon">{icon}</span>{label}{label === "Safety Alerts" && <b className="nav-count">4</b>}</Link>)}</nav><div className="sidebar-bottom"><div className="shift-card"><span className="shift-pulse" /><div><strong>Day shift active</strong><small>07:00 — 19:00 IST</small></div></div><a className="sidebar-help" href="mailto:safety-ops@minesafe.example">Need help? <span>Contact safety ops ↗</span></a></div></aside><div className="dashboard-main"><header className="dashboard-header"><div className="mobile-brand"><Brand /></div><div className="header-title"><p>MineSafe / Safety operations</p><h1>Incidents</h1></div><div className="header-actions"><div className="site-selector"><span className="site-pin">+</span><span><small>Current site</small>Singareni Mine — Site 04</span></div><span className="header-divider" /><span className="avatar">RK</span></div></header><main className="dashboard-content">{children}</main><footer className="dashboard-footer"><span>MineSafe Operations Console v1.0</span><span>Last system sync: 10:42:18 IST <i /></span></footer></div></div>; }
export default function IncidentsPage() {
  const [query, setQuery] = useState("");
  const [severity, setSeverity] = useState<Severity | "All">("All");
  const [status, setStatus] = useState<IncidentStatus | "All">("All");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  useEffect(() => {
    const id = new URLSearchParams(window.location.search).get("incident");
    startTransition(() => setSelectedId(id));
  }, []);
  const filtered = incidents.filter((incident) => [incident.id, incident.type, incident.location, incident.reportedBy].join(" ").toLowerCase().includes(query.toLowerCase()) && (severity === "All" || incident.severity === severity) && (status === "All" || incident.status === status));
  const selected = incidents.find((incident) => incident.id === selectedId);
  if (selected) return <Shell><section className="management-intro"><div><p className="dashboard-eyebrow"><span /> Incident details</p><h2>{selected.id}</h2><p>Review the report, response timeline, and related safety context.</p></div><Link className="button action-primary" href="/dashboard/incidents/new">Report another <span>↗</span></Link></section><section className="detail-layout"><article className="panel incident-detail-card"><div className="detail-header"><div><p className="panel-kicker">{selected.type} · {selected.location}</p><h2>{selected.description}</h2></div><span className={`risk risk-${selected.severity.toLowerCase()}`}>{selected.severity}</span></div><div className="detail-grid"><div><small>Status</small><strong>{selected.status}</strong></div><div><small>Reported by</small><strong>{selected.reportedBy}</strong></div><div><small>Date and time</small><strong>{selected.dateTime}</strong></div><div><small>People involved</small><strong>{selected.peopleInvolved}</strong></div></div><div className="detail-section"><p className="panel-kicker">Immediate actions</p><p>{selected.immediateAction}</p></div><div className="detail-section"><p className="panel-kicker">Witnesses</p><p>{selected.witnesses}</p></div></article><aside className="panel timeline-card"><p className="panel-kicker">Investigation status</p><h2>Response timeline</h2><ol className="timeline"><li><strong>Reported</strong><span>{selected.dateTime}</span></li><li><strong>Area made safe</strong><span>04 Sep · 09:24</span></li><li><strong>Assigned for review</strong><span>04 Sep · 09:31</span></li></ol><Link className="back-link" href="/dashboard/incidents">← Back to incidents</Link></aside></section><section className="panel related-alerts"><div className="panel-header"><div><p className="panel-kicker">Safety context</p><h2>Related safety alerts</h2></div></div><p>No additional related alerts have been linked to this incident in demo mode.</p></section></Shell>;
  return <Shell><section className="management-intro"><div><p className="dashboard-eyebrow"><span /> Incident management</p><h2>Incidents <span className="title-count">{incidents.length}</span></h2><p>Track reports from first notification through investigation and closeout.</p></div><Link className="button action-primary" href="/dashboard/incidents/new">Report incident <span>↗</span></Link></section><section className="management-stats"><div><strong>{incidents.length}</strong><span>Total incidents</span></div><div><strong>{incidents.filter((incident) => incident.status === "Open").length}</strong><span>Open incidents</span></div><div><strong>{incidents.filter((incident) => incident.status === "Under investigation").length}</strong><span>Under investigation</span></div><div><strong>{incidents.filter((incident) => incident.status === "Resolved" || incident.status === "Closed").length}</strong><span>Resolved</span></div></section><section className="panel management-panel"><div className="filter-bar"><input aria-label="Search incidents" placeholder="Search ID, type, location, or reporter" value={query} onChange={(event) => setQuery(event.target.value)} /><select aria-label="Filter incidents by severity" value={severity} onChange={(event) => setSeverity(event.target.value as Severity | "All")}>{severities.map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Filter incidents by status" value={status} onChange={(event) => setStatus(event.target.value as IncidentStatus | "All")}>{statuses.map((value) => <option key={value}>{value}</option>)}</select></div><div className="incident-table-wrap"><table className="management-table"><thead><tr><th>Incident ID</th><th>Type</th><th>Location</th><th>Severity</th><th>Reported by</th><th>Date / time</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.map((incident) => <tr key={incident.id}><td><strong>{incident.id}</strong></td><td>{incident.type}</td><td>{incident.location}</td><td><span className={`risk risk-${incident.severity.toLowerCase()}`}>{incident.severity}</span></td><td>{incident.reportedBy}</td><td>{incident.dateTime}</td><td>{incident.status}</td><td><Link className="row-action" href={`/dashboard/incidents?incident=${incident.id}`}>View ↗</Link></td></tr>)}</tbody></table>{filtered.length === 0 && <div className="empty-state"><strong>No incidents match these filters.</strong><p>Try broadening your search.</p></div>}</div></section></Shell>;
}
