"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import "../../dashboard.css";

const nav = [["Overview", "/dashboard", "▦"], ["Live Monitoring", "/dashboard/monitoring", "◉"], ["Vehicles", "/dashboard/vehicles", "▱"], ["Workers", "/dashboard/workers", "♙"], ["Safety Alerts", "/dashboard/alerts", "△"], ["Analytics", "/dashboard/analytics", "⌁"], ["Reports", "/dashboard/reports", "▤"], ["Settings", "/dashboard/settings", "⚙"]];
function Brand() { return <Link className="dashboard-brand" href="/"><span className="dashboard-logo" aria-hidden="true"><i /><i /><i /></span><span>Mine<span>Safe</span></span></Link>; }
function Shell({ children }: { children: React.ReactNode }) { return <div className="dashboard-shell management-page"><aside className="dashboard-sidebar"><Brand /><div className="sidebar-label">Workspace</div><nav>{nav.map(([label, href, icon]) => <Link href={href} key={label}><span className="sidebar-text-icon">{icon}</span>{label}{label === "Safety Alerts" && <b className="nav-count">4</b>}</Link>)}</nav><div className="sidebar-bottom"><div className="shift-card"><span className="shift-pulse" /><div><strong>Day shift active</strong><small>07:00 — 19:00 IST</small></div></div><a className="sidebar-help" href="mailto:safety-ops@minesafe.example">Need help? <span>Contact safety ops ↗</span></a></div></aside><div className="dashboard-main"><header className="dashboard-header"><div className="mobile-brand"><Brand /></div><div className="header-title"><p>MineSafe / Safety operations</p><h1>Report incident</h1></div><div className="header-actions"><div className="site-selector"><span className="site-pin">+</span><span><small>Current site</small>Singareni Mine — Site 04</span></div><span className="header-divider" /><span className="avatar">RK</span></div></header><main className="dashboard-content">{children}</main><footer className="dashboard-footer"><span>MineSafe Operations Console v1.0</span><span>Demo mode · No data sent to a backend</span></footer></div></div>; }

export default function NewIncidentPage() {
  const [submittedId, setSubmittedId] = useState<string | null>(null);
  const [error, setError] = useState("");
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; if (!form.checkValidity()) { setError("Complete all required fields before submitting."); form.reportValidity(); return; } setError(""); setSubmittedId(`INC-${Math.floor(249 + Math.random() * 50)}`); }
  return <Shell>{submittedId ? <section className="success-panel incident-success"><span className="success-mark">✓</span><div><p className="panel-kicker">Incident submitted</p><h2>Report {submittedId} created.</h2><p>Your report is ready for the safety operations team to review. This demo submission has not been sent to a backend.</p><div className="utility-actions"><Link className="button action-primary" href={`/dashboard/incidents?incident=${submittedId}`}>View incident <span>↗</span></Link><button className="secondary-action" onClick={() => setSubmittedId(null)}>Create another</button></div></div></section> : <><section className="utility-intro"><p className="dashboard-eyebrow"><span /> Incident management</p><h2>Report an incident.</h2><p>Record what happened, who was involved, and what action was taken so your team can respond with clarity.</p></section><form className="panel incident-form management-form" onSubmit={submit} noValidate><div className="panel-header"><div><p className="panel-kicker">New incident</p><h2>Incident details</h2></div><span className="form-required">* Required</span></div><div className="form-grid"><label>Incident type *<select required defaultValue=""><option value="" disabled>Select type</option><option>Near miss</option><option>Worker injury</option><option>Equipment issue</option><option>Environmental</option><option>Vehicle event</option></select></label><label>Location *<select required defaultValue=""><option value="" disabled>Select location</option><option>Zone A</option><option>Zone B</option><option>Zone C</option><option>Sector 7</option><option>North Tunnel</option><option>Haul Road 03</option></select></label><label>Date *<input required type="date" defaultValue="2026-09-04" /></label><label>Time *<input required type="time" defaultValue="10:42" /></label><label>Severity *<select required defaultValue="Medium"><option>Critical</option><option>High</option><option>Medium</option><option>Low</option></select></label><label>People involved<input placeholder="Names or team identifiers" /></label><label className="form-full">Description *<textarea required rows={5} placeholder="Describe what happened and the conditions at the time." /></label><label className="form-full">Immediate action taken<textarea rows={4} placeholder="Describe isolation, first aid, notifications, or other action." /></label><label className="form-full">Witnesses<input placeholder="Names and contact details, if available" /></label><label className="form-full attachment-field">Attachment (optional)<input type="file" /><small>Demo UI only. Files are not uploaded.</small></label></div>{error && <p className="form-error" role="alert">{error}</p>}<div className="form-footer"><Link className="secondary-action" href="/dashboard/incidents">Cancel</Link><button className="button action-primary" type="submit">Submit incident <span>↗</span></button></div></form></>}</Shell>;
}
