"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import "./dashboard.css";

const sections = [
  ["Overview", "/dashboard", "▦"], ["Live Monitoring", "/dashboard/monitoring", "◉"], ["Vehicles", "/dashboard/vehicles", "▱"], ["Workers", "/dashboard/workers", "♙"],
  ["Safety Alerts", "/dashboard/safety-alerts", "△"], ["Analytics", "/dashboard/analytics", "⌁"], ["Reports", "/dashboard/reports", "▤"], ["Settings", "/dashboard/settings", "⚙"],
];

const pageData: Record<string, { eyebrow: string; title: string; description: string; cards: [string, string, string][] }> = {
  Vehicles: { eyebrow: "Fleet overview", title: "Vehicle operations", description: "Track movement, status, and risk across every vehicle on site.", cards: [["38", "Vehicles on site", "All vehicles reporting"], ["31", "Currently moving", "82% of active fleet"], ["02", "Needs attention", "Review flagged routes"]] },
  Workers: { eyebrow: "People on site", title: "Worker safety", description: "Keep every crew member accounted for, briefed, and supported throughout the shift.", cards: [["247", "Active workers", "+12 from last shift"], ["04", "Zones occupied", "Across 3 active levels"], ["100%", "Accounted for", "Last check-in 10:39"]] },
  "Safety Alerts": { eyebrow: "Attention required", title: "Safety alerts", description: "Review active conditions and keep critical issues moving toward resolution.", cards: [["04", "Open alerts", "1 critical"], ["01", "Critical", "Requires immediate action"], ["12", "Resolved today", "Average response 8 min"]] },
  Analytics: { eyebrow: "Safety intelligence", title: "Operational analytics", description: "See the patterns behind site conditions and make better-informed safety decisions.", cards: [["18", "Current risk score", "↓ 6% from yesterday"], ["94%", "Checklist completion", "+4% this week"], ["08m", "Avg. response time", "↓ 2 min this month"]] },
  Reports: { eyebrow: "Documentation", title: "Safety reports", description: "Create, review, and share the records your operation needs to stay accountable.", cards: [["24", "Reports this month", "6 awaiting review"], ["18", "Completed", "75% of monthly total"], ["06", "Awaiting review", "Next due today"]] },
  Settings: { eyebrow: "Workspace controls", title: "Settings", description: "Manage site preferences, alert rules, and the operating standards for your team.", cards: [["04", "Active zones", "Site 04 configuration"], ["12", "Alert rules", "3 recently updated"], ["06", "Team roles", "Safety access managed"]] },
};

function Brand() { return <Link className="dashboard-brand" href="/"><span className="dashboard-logo" aria-hidden="true"><i /><i /><i /></span><span>Mine<span>Safe</span></span></Link>; }

export default function SectionPage({ section }: { section: keyof typeof pageData }) {
  const pathname = usePathname();
  const data = pageData[section];
  return <div className="dashboard-shell"><aside className="dashboard-sidebar"><Brand /><div className="sidebar-label">Workspace</div><nav>{sections.map(([label, href, icon]) => <Link className={pathname === href ? "active" : ""} href={href} key={label}><span className="sidebar-text-icon">{icon}</span>{label}{label === "Safety Alerts" && <b className="nav-count">4</b>}</Link>)}</nav><div className="sidebar-bottom"><div className="shift-card"><span className="shift-pulse" /><div><strong>Day shift active</strong><small>07:00 — 19:00 IST</small></div></div><button className="sidebar-help">Need help? <span>Contact safety ops ↗</span></button></div></aside><div className="dashboard-main"><header className="dashboard-header"><div className="mobile-brand"><Brand /></div><div className="header-title"><p>MineSafe / Operations</p><h1>{data.title}</h1></div><div className="header-actions"><div className="site-selector"><span className="site-pin">+</span><span><small>Current site</small>Singareni Mine — Site 04</span></div><span className="header-divider" /><button className="icon-button" aria-label="Notifications">◌</button><div className="profile"><span className="avatar">RK</span><span><strong>Ravi Kumar</strong><small>Safety operator</small></span></div></div></header><main className="dashboard-content"><section className="welcome-row"><div><p className="dashboard-eyebrow"><span /> Friday, 04 September 2026 · 10:42 IST</p><h2>{data.title}</h2><p className="welcome-text">{data.description}</p></div><div className="system-status"><i /> SYSTEM OPERATIONAL</div></section><section className="section-page-cards">{data.cards.map(([value, label, detail]) => <article className="metric-card" key={label}><p>{label}</p><strong>{value}</strong><span className="metric-detail detail-green">↗ {detail}</span></article>)}</section><section className="panel section-workspace" id={section === "Reports" ? "report-generation" : undefined}><div className="panel-header"><div><p className="panel-kicker">{data.eyebrow}</p><h2>{section === "Settings" ? "Workspace configuration" : "Site 04 activity"}</h2></div><span className="trend-change">Updated just now</span></div><div className="section-placeholder"><div className="placeholder-symbol">{section === "Safety Alerts" ? "△" : section === "Reports" ? "▤" : section === "Analytics" ? "⌁" : "◉"}</div><div><h3>{section === "Settings" ? "Your workspace is configured" : `Your ${section.toLowerCase()} view is ready`}</h3><p>Mock operational data is ready to connect to this workspace when the MineSafe data layer is introduced.</p></div><button className="panel-link">Explore workspace ↗</button></div></section></main><footer className="dashboard-footer"><span>MineSafe Operations Console v1.0</span><span>Last system sync: 10:42:18 IST <i /></span></footer></div></div>;
}
